### ISSUE TITLE
Run trainval_net_SCL.py with custom dataset raises RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0.

### ISSUE THREAD

**Issue by SkeletonOne** [harsh-99/SCL#21]
Traceback (most recent call last):
  File "trainval_net_SCL.py", line 183, in <module>
    data_s = next(data_iter_s)
  File "/home/skl/anaconda3/envs/python27/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/home/skl/anaconda3/envs/python27/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/skl/anaconda3/envs/python27/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/skl/anaconda3/envs/python27/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 138, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/skl/anaconda3/envs/python27/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 115, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 426 and 384 in dimension 2 at /pytorch/aten/src/TH/generic/THTensorMath.c:3586

However, with the same setting, Strong-Weak DA F-RCNN can be trained.

**Comment by harsh-99** [comment]
Hi, I think it's data loader problem so it should be coming for both scl and strong-weak. Maybe you should try to find for which data point exactly this problem is coming. And for training strong-weak which code did you use?

**Comment by SkeletonOne** [comment]
@harsh-99 I used the strong-weak code in this repository. Just with:

CUDA_VISIBLE_DEVICES=$1 python trainval_net_global_local.py --cuda --net vgg16 --dataset mydataset_source --dataset_t mydataset_target --gc --lc --save_dir output

**Comment by SkeletonOne** [comment]
I've figured it out. The SCL do not support batch size other than 1. Because if batch size = 2, "pooled_feat" will add 256 channels after each one in "feat1, feat2, feat3". This will cause a shape mismatch in "netD_inst" because the channels are hard-coded like 2048+128+128+128. So I just changed the cfgs and train it for a longer time. Still appreciate your great work!

**Comment by harsh-99** [comment]
@SkeletonOne  Thanks a lot for pointing out that. I will try to add the functionality of batch size greater 1. In case if you have done that, feel free to send PR.
