### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by jizefeng0810** [harsh-99/SCL#9]
`ImportError: 'No module named 'lib.model.utils.cython_bbox''

I only find this file: cython_bbox.cpython-36m-x86_64-linux-gnu.so
How can I solve it?

**Comment by jizefeng0810** [comment]
Could you give me your environment?

**Comment by jizefeng0810** [comment]
I change python version:python=3.6.
Error:
Traceback (most recent call last):
  File "trainval_net_SCL.py", line 21, in <module>
    from lib.roi_data_layer.roidb import combined_roidb
  File "/home/jizefeng/code/SCL-master/lib/roi_data_layer/roidb.py", line 9, in <module>
    from datasets.factory import get_imdb
  File "/home/jizefeng/code/SCL-master/lib/datasets/factory.py", line 14, in <module>
    from datasets.pascal_voc import pascal_voc
  File "/home/jizefeng/code/SCL-master/lib/datasets/pascal_voc.py", line 23, in <module>
    from .imdb import imdb
  File "/home/jizefeng/code/SCL-master/lib/datasets/imdb.py", line 15, in <module>
    from lib.model.utils.cython_bbox import bbox_overlaps
  File "__init__.pxd", line 918, in init model.utils.cython_bbox
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

**Comment by jizefeng0810** [comment]
ImportError: /home/jizefeng/code/SCL-master/lib/model/roi_crop/_ext/roi_crop/_roi_crop.so: undefined symbol: __cudaPopCallConfiguration

**Comment by harsh-99** [comment]
Hi, 
As mentioned in readme file of https://github.com/jwyang/faster-rcnn.pytorch/blob/master/README.md it's important to use pytorch 0.4 for this code base. I have also faced such problems with other pytorch environment. In case if you are using pytorch 0.4 please also tell me python version, cuda version.

**Comment by jizefeng0810** [comment]
pytorch0.4.0 and cuda9.2

**Comment by harsh-99** [comment]
Was there any kind of error, when you executed make.sh bash file present in lib?
